version: '3.3'
services:

  database:
    image: "mysql/mysql-server:5.7"
    environment:      
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lportal
      - MYSQL_USER=dxpcloud
      - MYSQL_PASSWORD=dxpcloud
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8
    volumes:
      - type: bind
        source: ./backups/lportal.sql
        target: /docker-entrypoint-initdb.d/lportal.sql
      - type: bind
        source: ./upgrade_output
        target: /upgrade_output

  liferay:
    image: "liferaycloud/liferay-dxp:7.2.10-sp1-fp4-3.0.18"
    environment:
      - LCP_PROJECT_ENVIRONMENT=local
      - LIFERAY_JAVA_OPTS=-Xms8g -Xmx8g
      - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11311
    volumes:
      - type: bind
        source: ./liferay_scripts
        target: /lcp-container/script/local
      # - type: bind
      #   source: ./liferay_hotfix
      #   target: /lcp-container/hotfix/local
    depends_on:
      - database